### ISSUE TITLE
Allow user to choose between Camera1 and Camera2 API

### ISSUE THREAD

**Issue by zpapp** [infinum/Android-GoldenEye#24]
Hi,

I'd like to allow the users of my app to opt out of using Camera2 even if it's available to use. To help with this, I'd like this library to

1) Tell me if using Camera2 is even an option.

2) Allow me to build a `GoldenEye` instance using Camera1 (i.e. `GoldenEye1Impl`) even if the device supports Camera2.

Looking at the code it seems to me this is currently not possible (please correct me if I am mistaken), even though you already have most of the building blocks to make this possible. Basically, I'd like to bundle that `if` condition in `GoldenEye.Builder.build()` into a boolean variable (e.g. `GoldenEye.isCamera2Supported`), and add a builder function (e.g. `GoldenEye.Builder.forceCamera1()`) that would force the `build()` function to return `GoldenEye1Impl` regardless of anything else.

Would you be willing to add this feature? And if so, would you like me to submit the necessary changes in a pull request?

**Comment by domagojkorman** [comment]
Hi @zpapp ,

could you please explain to me what is the benefit of this feature? 

Generally, the idea behind the library is to not bother whether in the background it uses Camera1 or Camera2 API. Also, I noticed some issues regarding VideoRecording with newer devices using Camera1 API.

**Comment by zpapp** [comment]
Hi,

thanks for the quick response!

The most obvious benefit is that it will give the users a way out when (not "if" :) ) it turns out that the `isIncompatibleDevice` list is incomplete.

A less obvious benefit is that a user may prefer Camera1 for any number of subjective reasons. For example, the authors of Fotoapparat, a library I am sure you are familiar with, decided to not use Camera2 at all because it was "[not as performant](https://github.com/RedApparat/Fotoapparat/issues/231#issuecomment-375387287)" as Camera1.

Not strictly related to this feature request but I am actually very curious what you think of this performance issue. Were you aware that Fotoapparat dropped Camera2 due to this? Do you think they were mistaken?

> idea behind the library is to not bother whether in the background it uses Camera1 or Camera2 API

Obviously it's not for me to say what goals you should set but from my perspective this seems unnecessarily ambitious. If you manage to create a library that provides a relatively safe and convenient wrapper around both Camera1 and Camera2, that will be an amazing achievement in itself. I sure as hell wouldn't want the additional responsibility of deciding which one is "best" on any one of the thousands of Android device models, multiplied by all the possible Android versions.

> I noticed some issues regarding VideoRecording with newer devices using Camera1 API.

Yes, I saw your comments about this on Reddit. I don't see this as a counter-argument to my request. I am not asking you to force the user to use Camera1 instead of Camera2, I am asking for the option to explicitly choose which one they prefer.

**Comment by domagojkorman** [comment]
> Not strictly related to this feature request but I am actually very curious what you think of this performance issue. Were you aware that Fotoapparat dropped Camera2 due to this? Do you think they were mistaken?

I am not sure what they mean by "not as performant". I did notice that Camera2 required much more work though.

To keep it short, I agree with your points. This is really short feature request so I will do it myself sometimes today.

Thank you for the explanation.

**Comment by zpapp** [comment]
Thanks for adding the `forceCamera1Api` function!

Could you please also expose the condition that is otherwise (in the absence of `forceCamera1Api`) used to select Camera2, as a boolean property on `GoldenEye` or `GoldenEye.Builder`? I would use this to offer the choice between Camera1 and Camera2 to the user only if the library considers Camera2 a valid option.

So basically this (at the moment):

`Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && isLegacyCamera().not() && IncompatibleDevicesUtils.isIncompatibleDevice(Build.MODEL).not()`

**Comment by domagojkorman** [comment]
Could you please explain the use case and why you think this is needed? I am not sure why would the user ever want to choose manually between Camera1 and Camera2.

**Comment by domagojkorman** [comment]
@zpapp while I do not agree with you that the end user should have this decision because they don't even know what is Camera1 and Camera2, I think that manual selection feature can be improved and I am OK with it.

**Comment by zpapp** [comment]
> they don't even know what is Camera1 and Camera2

They don't need to. All they need to know there is an option they can change that may make their camera work better.

> I think that manual selection feature can be improved and I am OK with it.

Great, thanks!

**Comment by domagojkorman** [comment]
Exposed methods
- `GoldenEye.preferredCameraApi(Context)` - check which Camera API should be used
- `setCameraApi(CameraApi)` - manually set whatever Camera API you want to use. It throws exception if Camera2 is passed on devices older than Lollipop where Camera2 does not exist.
