### ISSUE TITLE
Enhancement request: Ability to pass multiple surfaces while opening camera 

### ISSUE THREAD

**Issue by ankitgusai** [infinum/Android-GoldenEye#28]
As the title suggest if `goldenEye.open(...)` could accept multiple surfaces the it would be possible to render image on `TextureView` as well as process it at the same time.

**Comment by domagojkorman** [comment]
Is it possible to add multiple surfaces to the Camera1 API? I don't think it is possible.

The idea of the lib is to be compatible with both Camera APIs so this feature request looks like it would break the API.

**Comment by domagojkorman** [comment]
Closing the issue due to inactivity.

I also don't think this would be good feature to cover because it would for sure break the API on Camera1 side.
